export 'package:widgets_app/presentation/screens/animated/animated_screen.dart';
export 'package:widgets_app/presentation/screens/app_tutorial/app_tutorail_screen.dart';
export 'package:widgets_app/presentation/screens/buttons/buttons_screen.dart';
export 'package:widgets_app/presentation/screens/cards/cards_screen.dart';
export 'package:widgets_app/presentation/screens/home/home_screen.dart';
export 'package:widgets_app/presentation/screens/infinit_scroll/iniginite_scroll_screen.dart';
export 'package:widgets_app/presentation/screens/progrees/progrees_screen.dart';
export 'package:widgets_app/presentation/screens/snackbar/snackbar_screen.dart';
export 'package:widgets_app/presentation/screens/ui_cointrols/ui_controls_screen.dart';
